// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpp-4tpLmsVS1W2_hQxO_6f3qDSTRArS4',
    appId: '1:122026906326:web:05615c0362e70ab2152f77',
    messagingSenderId: '122026906326',
    projectId: 'first-flutter-app-bf93d',
    authDomain: 'first-flutter-app-bf93d.firebaseapp.com',
    storageBucket: 'first-flutter-app-bf93d.firebasestorage.app',
    measurementId: 'G-60EB83Y6LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxs9MJPTZyuyWKcXMN46wrnCQWfohxBl8',
    appId: '1:122026906326:android:12e321049adcf716152f77',
    messagingSenderId: '122026906326',
    projectId: 'first-flutter-app-bf93d',
    storageBucket: 'first-flutter-app-bf93d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV4Cm4fZM0vq5grtbUjX3dDKZMxzFzDXI',
    appId: '1:122026906326:ios:74b450171820dd8e152f77',
    messagingSenderId: '122026906326',
    projectId: 'first-flutter-app-bf93d',
    storageBucket: 'first-flutter-app-bf93d.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV4Cm4fZM0vq5grtbUjX3dDKZMxzFzDXI',
    appId: '1:122026906326:ios:74b450171820dd8e152f77',
    messagingSenderId: '122026906326',
    projectId: 'first-flutter-app-bf93d',
    storageBucket: 'first-flutter-app-bf93d.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpp-4tpLmsVS1W2_hQxO_6f3qDSTRArS4',
    appId: '1:122026906326:web:a4e8ab01e4eb689e152f77',
    messagingSenderId: '122026906326',
    projectId: 'first-flutter-app-bf93d',
    authDomain: 'first-flutter-app-bf93d.firebaseapp.com',
    storageBucket: 'first-flutter-app-bf93d.firebasestorage.app',
    measurementId: 'G-Y63QGN5QW0',
  );
}
